### ISSUE TITLE
Base64 encode from bytes array return wrong output

### ISSUE THREAD

**Issue by tbrixi** [Meychi/ASCrypt#5]
var out:String = Base64.encode(bytes);
in output missing one character on end of string "....vVfeey2z=" ,
correct Base64 encoding return one more char  "....vVfeey2zo="

**Comment by madovsky** [comment]
sorry I don't know if the issue I found comes from Bas64 or UTF8 so I continue this thread.
trying to encode and decode this line "BooRec_2015-2-6_17-13-52"
I got this decoded "BooRec_2015-2-6_17-13-0" after used Base64 and UTF8 classes
weirdly it works well with non latin and special chars.

**Comment by Meychi** [comment]
Thanks for the details, i think i found the issue from Base64.encode, i'll do some tests and then commit the fix.

**Comment by Meychi** [comment]
Should be fixed now.

**Comment by ROBERT-MCDOWELL** [comment]
Ok  I will test it as soon as I can thanks
